### ISSUE TITLE
[CLOSED] [Closes #5] Switch to MyEtherAPI.com for access to blockchain

### ISSUE THREAD

**Issue by JonathonDunford** [Agorex-io/FrontEnd#6]
<a href="https://github.com/freeatnet"><img src="https://avatars0.githubusercontent.com/u/138289?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [freeatnet](https://github.com/freeatnet)**
_Wednesday Jan 10, 2018 at 00:32 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/forkdelta/forkdelta.github.io/pull/6_

----

----

_**[freeatnet](https://github.com/freeatnet)** included the following code: https://github.com/forkdelta/forkdelta.github.io/pull/6/commits_

**Comment by JonathonDunford** [comment]
<a href="https://github.com/freeatnet"><img src="https://avatars0.githubusercontent.com/u/138289?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [freeatnet](https://github.com/freeatnet)**
_Wednesday Jan 10, 2018 at 00:32 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Blocked by https://github.com/MyEtherWallet/myetherapi/issues/1#issuecomment-355896945. If they block IP addresses at random, that's a no-go. Waiting on their response.

**Comment by JonathonDunford** [comment]
<a href="https://github.com/freeatnet"><img src="https://avatars0.githubusercontent.com/u/138289?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [freeatnet](https://github.com/freeatnet)**
_Thursday Jan 18, 2018 at 18:37 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I've emailed a bit with @tayvano and have been assured that only specific offending IPs are blocked. We should be ok to proceed.

**Comment by JonathonDunford** [comment]
<a href="https://github.com/JonathonDunford"><img src="https://avatars1.githubusercontent.com/u/5281151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JonathonDunford](https://github.com/JonathonDunford)**
_Thursday Jan 18, 2018 at 22:56 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

"If you hit over 200 requests / minute, you'll be blocked for ~1hr, regardless of region."

Need to make sure it's under 200 rpm?

**Comment by JonathonDunford** [comment]
<a href="https://github.com/freeatnet"><img src="https://avatars0.githubusercontent.com/u/138289?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [freeatnet](https://github.com/freeatnet)**
_Friday Jan 19, 2018 at 00:06 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@JonathonDunford This frontend currently updates the latest block number about every 5 seconds, otherwise only needing a node to send transactions. Doesn't seem like it would ever hit anywhere close to 200 rpm.

**Comment by tayvano** [comment]
The blocktimes are approximately 15 seconds so pinging for the block number every 5 seconds is 3x as excessive as it needs to be. 

Our outrageous server bill thanks you for your consideration.

**Comment by JonathonDunford** [comment]
@tayvano Hey! Thanks for dropping in.

I am no longer with ForkDelta, but the team here is launching a new DEX. Do you care to open an issue here to make sure that consideration change makes it into our new exchange?

I appreciate all of the work you have done on MyCrypto!
